version: '3'

services:

  #----------------------------------------------------------------------------------------
  #  RabbitMQ Message Broker
  #----------------------------------------------------------------------------------------
  rabbit:
    build: .
    image: clintelli-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"

  #----------------------------------------------------------------------------------------
  #  PostgreSQL Database
  #----------------------------------------------------------------------------------------
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - clintelli_private_docker_network



  #----------------------------------------------------------------------------------------
  #  Minio S3-like Object Storage
  #----------------------------------------------------------------------------------------

  minio1:
    image: minio/minio
    volumes:
      - minio-data1:/export
    ports:
    - "9001:9000"
    env_file:
      - .env
    networks:
      - clintelli_private_docker_network
    command: server http://minio{1...4}/export

  minio2:
    image: minio/minio
    volumes:
      - minio-data2:/export
    ports:
    - "9002:9000"
    env_file:
      - .env
    networks:
      - clintelli_private_docker_network
    command: server http://minio{1...4}/export

  minio3:
    image: minio/minio
    volumes:
      - minio-data3:/export
    ports:
      - "9003:9000"
    env_file:
      - .env
    networks:
      - clintelli_private_docker_network
    command: server http://minio{1...4}/export

  minio4:
    image: minio/minio
    volumes:
      - minio-data4:/export
    ports:
      - "9004:9000"
    env_file:
      - .env
    networks:
      - clintelli_private_docker_network
    command: server http://minio{1...4}/export


#----------------------------------------------------------------------------------------
#  VOLUMES AND NETWORKING
#----------------------------------------------------------------------------------------

volumes:
  minio-data1:
  minio-data2:
  minio-data3:
  minio-data4:

networks:
  clintelli_private_docker_network:
    external: true
